#include "include/flags.hpp"

DEFINE_bool(h, false, help_message);
DEFINE_uint64(pattern_width, 9, pattern_dimensions_message);
DEFINE_uint64(pattern_height, 6, pattern_dimensions_message);
DEFINE_double(board_square_size_cm, 3.6, board_square_size_message);
DEFINE_uint64(num_boards_before_dynamic_projector_calib, 8, nboards_before_dynamic_message);
DEFINE_uint64(num_boards_final_projector_calib, 5, nboards_final_proj_calib_message);
DEFINE_uint64(minimum_frames, 8, minimum_frames_message);
DEFINE_uint64(delay_between_frames, 1000, delay_frames_message);
DEFINE_double(minimum_board_motion_px, 15.0, board_motion_message);
DEFINE_string(calibration_output_dir, "", calibration_output_dir_message);
DEFINE_double(projector_offset_y_scale, 0.9, projector_offset_scale_message);
DEFINE_uint64(projected_circle_radius, 30, projector_circle_radius_message);
DEFINE_double(static_projector_spacing_px, 120.0, "Static asymmetric-grid spacing in projector pixels; reduce to fit the white board area.");
DEFINE_double(static_projector_center_x, 0.5, "Static grid center X as a fraction of projector image width.");
DEFINE_double(static_projector_center_y, 0.5, "Static grid center Y as a fraction of projector image height.");
DEFINE_double(minimum_projector_board_position_span, 0.1, "Minimum normalized chessboard-centroid span for static projector board-pose diversity.");
DEFINE_double(minimum_projector_pattern_span, 0.2, "Minimum normalized diagonal span of selected projector circle centers (not centroid movement).");
DEFINE_double(projector_detection_threshold, 210.0, "Brightness threshold in camera pixels (0..255); -1 uses global Otsu. Restart calibration after changes.");
DEFINE_double(projector_blob_min_area, 25.0, "Minimum detected circle blob area in camera pixels squared.");
DEFINE_double(projector_blob_max_area, 5000.0, "Maximum detected circle blob area in camera pixels squared.");
DEFINE_double(projector_blob_min_circularity, 0.0, "Minimum circle blob circularity (0 disables; up to 1).");
DEFINE_double(projector_blob_min_inertia, 0.1, "Minimum circle blob inertia ratio (0 disables; up to 1). Lower permits more tilt.");
DEFINE_double(projector_blob_min_convexity, 0.95, "Minimum circle blob convexity (0 disables; up to 1).");
DEFINE_uint64(projector_settle_ms, 100, "Display settling time before capture, milliseconds.");
DEFINE_uint64(projector_discard_frames, 2, "Camera frames discarded after pattern presentation to reduce buffered-frame mismatch.");
DEFINE_bool(require_board_orientation, true, "Require an ArUco-anchored physical chessboard origin; maintain it only during continuous tracking.");
DEFINE_int32(board_aruco_dictionary, 8, "OpenCV ArUco dictionary index; 8 is DICT_6X6_50.");
DEFINE_int32(board_origin_aruco_id, 0, "Primary marker ID in the white square above/right of the intended first inner corner.");
DEFINE_int32(board_origin_secondary_aruco_id, 1, "Secondary marker ID in the white square below/left of the intended first inner corner.");
DEFINE_double(board_origin_marker_x_squares, 0.5, "Primary marker center X in square units from intended first inner corner.");
DEFINE_double(board_origin_marker_y_squares, -0.5, "Primary marker center Y in square units from intended first inner corner.");
DEFINE_double(board_secondary_marker_x_squares, -0.5, "Secondary marker center X in square units from intended first inner corner.");
DEFINE_double(board_secondary_marker_y_squares, 0.5, "Secondary marker center Y in square units from intended first inner corner.");
DEFINE_double(board_origin_marker_tolerance_squares, 0.6, "Maximum marker-layout error in chessboard square units.");
DEFINE_double(board_tracking_max_motion_squares, 1.5, "Maximum per-frame corner RMS movement in square units without an orientation marker.");
DEFINE_bool(use_projection_region, true, "Center the dynamic grid inside the configured physical white projection region.");
DEFINE_double(projection_region_width_cm, 37.0, "Physical white projection region width, centimeters (approximate hand measurement).");
DEFINE_double(projection_region_height_cm, 29.0, "Physical white projection region height, centimeters (approximate hand measurement).");
DEFINE_double(projection_region_top_cm, 25.5, "Top edge of white region below intended first inner corner, centimeters.");
DEFINE_double(projection_region_center_x_cm, 14.4, "White region center X from intended first inner corner, centimeters; 14.4 centers default 9x6 board.");
DEFINE_double(projector_smoothing_rate, 0.4, projector_smoothing_rate_message);
DEFINE_double(max_dynamic_stereo_rms, 3.0, dynamic_stereo_rms_message);
DEFINE_uint64(calibration_candidate_margin, 4, calibration_candidate_margin_message);
DEFINE_double(max_camera_per_view_rms, 2.0, max_camera_per_view_rms_message);
DEFINE_double(max_camera_rms, 1.5, max_camera_rms_message);
DEFINE_double(max_projector_per_view_rms, 3.0, max_projector_per_view_rms_message);
DEFINE_double(max_projector_rms, 2.5, max_projector_rms_message);
DEFINE_double(minimum_calibration_position_span, 0.25, minimum_calibration_position_span_message);
DEFINE_double(minimum_calibration_distance_ratio, 1.1, minimum_calibration_distance_ratio_message);
DEFINE_double(minimum_calibration_orientation_span_deg, 10.0, minimum_calibration_orientation_span_message);
