// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/position.proto

#include "proto/position.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)
namespace zaboom {
class people_positionDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<people_position>
      _instance;
} _people_position_default_instance_;
}  // namespace zaboom
namespace protobuf_proto_2fposition_2eproto {
void InitDefaultspeople_positionImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  {
    void* ptr = &::zaboom::_people_position_default_instance_;
    new (ptr) ::zaboom::people_position();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::zaboom::people_position::InitAsDefaultInstance();
}

void InitDefaultspeople_position() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultspeople_positionImpl);
}

::google::protobuf::Metadata file_level_metadata[1];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::zaboom::people_position, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::zaboom::people_position, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::zaboom::people_position, x_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::zaboom::people_position, y_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::zaboom::people_position, device_number_),
  ~0u,
  ~0u,
  ~0u,
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 8, sizeof(::zaboom::people_position)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::zaboom::_people_position_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "proto/position.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\024proto/position.proto\022\006zaboom\">\n\017people"
      "_position\022\t\n\001x\030\001 \003(\002\022\t\n\001y\030\002 \003(\002\022\025\n\rdevic"
      "e_number\030\003 \003(\t"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 94);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "proto/position.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_proto_2fposition_2eproto
namespace zaboom {

// ===================================================================

void people_position::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int people_position::kXFieldNumber;
const int people_position::kYFieldNumber;
const int people_position::kDeviceNumberFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

people_position::people_position()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_proto_2fposition_2eproto::InitDefaultspeople_position();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:zaboom.people_position)
}
people_position::people_position(const people_position& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_),
      _cached_size_(0),
      x_(from.x_),
      y_(from.y_),
      device_number_(from.device_number_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:zaboom.people_position)
}

void people_position::SharedCtor() {
  _cached_size_ = 0;
}

people_position::~people_position() {
  // @@protoc_insertion_point(destructor:zaboom.people_position)
  SharedDtor();
}

void people_position::SharedDtor() {
}

void people_position::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* people_position::descriptor() {
  ::protobuf_proto_2fposition_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_proto_2fposition_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const people_position& people_position::default_instance() {
  ::protobuf_proto_2fposition_2eproto::InitDefaultspeople_position();
  return *internal_default_instance();
}

people_position* people_position::New(::google::protobuf::Arena* arena) const {
  people_position* n = new people_position;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void people_position::Clear() {
// @@protoc_insertion_point(message_clear_start:zaboom.people_position)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  x_.Clear();
  y_.Clear();
  device_number_.Clear();
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool people_position::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:zaboom.people_position)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated float x = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(13u /* 13 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 1, 13u, input, this->mutable_x())));
        } else if (
            static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitiveNoInline<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, this->mutable_x())));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated float y = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(21u /* 21 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 1, 21u, input, this->mutable_y())));
        } else if (
            static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitiveNoInline<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, this->mutable_y())));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated string device_number = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->add_device_number()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->device_number(this->device_number_size() - 1).data(),
            static_cast<int>(this->device_number(this->device_number_size() - 1).length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "zaboom.people_position.device_number");
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:zaboom.people_position)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:zaboom.people_position)
  return false;
#undef DO_
}

void people_position::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:zaboom.people_position)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated float x = 1;
  for (int i = 0, n = this->x_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(
      1, this->x(i), output);
  }

  // repeated float y = 2;
  for (int i = 0, n = this->y_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(
      2, this->y(i), output);
  }

  // repeated string device_number = 3;
  for (int i = 0, n = this->device_number_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->device_number(i).data(), static_cast<int>(this->device_number(i).length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "zaboom.people_position.device_number");
    ::google::protobuf::internal::WireFormatLite::WriteString(
      3, this->device_number(i), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:zaboom.people_position)
}

::google::protobuf::uint8* people_position::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:zaboom.people_position)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated float x = 1;
  target = ::google::protobuf::internal::WireFormatLite::
    WriteFloatToArray(1, this->x_, target);

  // repeated float y = 2;
  target = ::google::protobuf::internal::WireFormatLite::
    WriteFloatToArray(2, this->y_, target);

  // repeated string device_number = 3;
  for (int i = 0, n = this->device_number_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->device_number(i).data(), static_cast<int>(this->device_number(i).length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "zaboom.people_position.device_number");
    target = ::google::protobuf::internal::WireFormatLite::
      WriteStringToArray(3, this->device_number(i), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:zaboom.people_position)
  return target;
}

size_t people_position::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:zaboom.people_position)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  // repeated float x = 1;
  {
    unsigned int count = static_cast<unsigned int>(this->x_size());
    size_t data_size = 4UL * count;
    total_size += 1 *
                  ::google::protobuf::internal::FromIntSize(this->x_size());
    total_size += data_size;
  }

  // repeated float y = 2;
  {
    unsigned int count = static_cast<unsigned int>(this->y_size());
    size_t data_size = 4UL * count;
    total_size += 1 *
                  ::google::protobuf::internal::FromIntSize(this->y_size());
    total_size += data_size;
  }

  // repeated string device_number = 3;
  total_size += 1 *
      ::google::protobuf::internal::FromIntSize(this->device_number_size());
  for (int i = 0, n = this->device_number_size(); i < n; i++) {
    total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
      this->device_number(i));
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void people_position::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:zaboom.people_position)
  GOOGLE_DCHECK_NE(&from, this);
  const people_position* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const people_position>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:zaboom.people_position)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:zaboom.people_position)
    MergeFrom(*source);
  }
}

void people_position::MergeFrom(const people_position& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:zaboom.people_position)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  x_.MergeFrom(from.x_);
  y_.MergeFrom(from.y_);
  device_number_.MergeFrom(from.device_number_);
}

void people_position::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:zaboom.people_position)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void people_position::CopyFrom(const people_position& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:zaboom.people_position)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool people_position::IsInitialized() const {
  return true;
}

void people_position::Swap(people_position* other) {
  if (other == this) return;
  InternalSwap(other);
}
void people_position::InternalSwap(people_position* other) {
  using std::swap;
  x_.InternalSwap(&other->x_);
  y_.InternalSwap(&other->y_);
  device_number_.InternalSwap(&other->device_number_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata people_position::GetMetadata() const {
  protobuf_proto_2fposition_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_proto_2fposition_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace zaboom

// @@protoc_insertion_point(global_scope)
